version: "3.9"

services:
  xai-backend:
    image: xai-yolo-backend:latest
    build:
      context: .
    container_name: xai-yolo-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
